export enum Actions {
  LOGIN = 'LOGIN',
  LOG_OUT = 'LOG_OUT',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  GET_USER = 'GET_USER',
  SIGN_UP = 'SIGN_UP',
  CLEAR_USER_ERRORS = 'CLEAR_USER_ERRORS',
  SET_USER_ERROR = 'SET_USER_ERROR',
}
